blank_issues_enabled: false
contact_links:
    - name: ğŸ’¬ ì§ˆë¬¸/ë…¼ì˜ (Discussions)
      url: https://github.com/<OWNER>/<REPO>/discussions
      about: ì§ˆë¬¸, ì•„ì´ë””ì–´ í† ë¡ ì€ Discussionsì—ì„œ ë…¼ì˜í•©ë‹ˆë‹¤.
